[package]
name = "cli_test"
version = "0.1.0"
edition = "2021"

[dependencies]
color-print = "0.3.6"
inquire = { version = "0.7.5", features = ["date"] }
serde = {version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
strum = "0.26.3"
strum_macros = "0.26.4"
